run:
  name: experiment_name
  source_hard: False
  preprocess_hard: False
  train_hard: True
  evaluate_hard: True

predict:

networks:
  tcn:
    weight_norm: True
  mlp:
  ar:

scoring:
  owa:
    naive2:
      #smape:
      #  yearly: 16.342
      #  quarterly: 11.012
      #  monthly: 14.427
      #  weekly: 9.161
      #  daily: 3.045
      #  hourly: 18.383
      #  global: 13.564
      #mase:
      #  yearly: 3.974
      #  quarterly: 1.371
      #  monthly: 1.063
      #  weekly: 2.777
      #  daily: 3.278
      #  hourly: 2.396
      #  global: 1.912
      #val set vv:
      smape:
        yearly: 19.251
        quarterly: 11.247
        monthly: 13.102
        weekly: 9.196
        daily: 2.778
        hourly: 41.399
        global: 13.738
      mase:
        yearly: 4.723
        quarterly: 1.378
        monthly: 1.036
        weekly: 2.898
        daily: 3.221
        hourly: 11.532
        global: 2.109

  metrics:
    mase: True
    smape: True
    owa: True
    mae: False
    rmse: False
    wape: False
    mape: False
  m4:

    #scale_mase: True
    horizons:
      yearly: 6
      quarterly: 8
      monthly: 18
      weekly: 13
      daily: 14
      hourly: 48
    periods:
      yearly: 1
      quarterly: 4
      monthly: 12
      weekly: 1
      daily: 1
      hourly: 24
      other: 1

tests:
  data:
    M4:
      Dtest: "GPTime/tests/data/M4test/Daily-test.csv"
      Htest: "GPTime/tests/data/M4test/Hourly-test.csv"
      Mtest: "GPTime/tests/data/M4test/Monthly-test.csv"
      Qtest: "GPTime/tests/data/M4test/Quarterly-test.csv"
      Wtest: "GPTime/tests/data/M4test/Weekly-test.csv"
      Ytest: "GPTime/tests/data/M4test/Yearly-test.csv"
      Dtrain: "GPTime/tests/data/M4train/Daily-train.csv"
      Htrain: "GPTime/tests/data/M4train/Hourly-train.csv"
      Mtrain: "GPTime/tests/data/M4train/Monthly-train.csv"
      Qtrain: "GPTime/tests/data/M4train/Quarterly-train.csv"
      Wtrain: "GPTime/tests/data/M4train/Weekly-train.csv"
      Ytrain: "GPTime/tests/data/M4train/Yearly-train.csv"
      smyl: "GPTime/tests/data/M4submissions/submission-118.csv"
      montero: "GPTime/tests/data/M4submissions/submission-245.csv"
      naive: "GPTime/tests/data/M4submissions/submission-Naive.csv"
      naive2: "GPTime/tests/data/M4submissions/submission-Naive2.csv"
    
figures:
  path: figures/
