path:
  #FRED: /work/erikde/data/processed/FRED
  #FRED_small: /work/erikde/data/processed/FRED_small
  M4: /work/erikde/data/processed/M4/
ts:
  min_length:
    yearly: 5
    quarterly: 10
    monthly: 26
    weekly: 52
    daily: 16
    hourly: 50
    other: 10
remove:
  zero: False
  zero_treshold: 0.8
  constant: False 