name: test_name
model_save_path: /work/erikde/models
result_path: /work/erikde
predictions_path: /work/erikde

results_path: GPTime/models/
val_set: False
scale: False
seasonal_init: False
global_model: False
lookback:

model_module: GPTime.networks.mlp
model_name: MLP
model_params_mlp:
  in_features: 256
  out_features: 1
  num_layers: 10
  n_hidden: 1024
  bias: True
  residual:
  res_block_size: 2
  skip_connections: False
  dropout: 0.2
  encode_frequencies: True
