run:
  name: experiment_name
  source_hard: False
  preprocess_hard: False
  train_hard: True
  evaluate_hard: True

path:
  m4_train: "GPTime/data/raw/M4/M4train/"
  m4_test: "GPTime/data/raw/M4/M4test/"
  logs: "logs"
  log_config: "configs/logging.yml"

source:
  path:
    FRED:
      meta: GPTime/data/meta/FRED/
      #raw: GPTime/data/raw/FRED/
      raw: /work/erikde/data/raw/FRED
    M4:
      raw_train: GPTime/data/raw/M4/M4train/
      raw_test: GPTime/data/raw/M4/M4test/
      meta: GPTime/data/meta/M4/M4-info.csv
  api:
    FRED:
      limit: 115
      sleep: 60 
  files_per_folder: 100
  samples_per_json: 2000


preprocess:
  path:
    #FRED: /work/erikde/data/processed/FRED
    #FRED_small: /work/erikde/data/processed/FRED_small
    M4: /work/erikde/data/processed/M4/
  ts:
    min_length:
      yearly: 5
      quarterly: 10
      monthly: 26
      weekly: 52
      daily: 16
      hourly: 50
      other: 10
  remove:
    zero: False
    zero_treshold: 0.8
    constant: False 

dataset:
  proportion: 1
  dataset_module: "GPTime.model.data"
  dataset_name: "TSDataset"
  #dataset_name: DummyDataset
  #dataset_name: MonteroMansoHyndmanSimpleDS
  #dataset_name: MonteroMansoHyndmanDS
  #dataset_name: FREDSimpleDS
  dataset_params:
    dataset_paths:
      #FRED: GPTime/data/processed/FRED
      #FRED_small: GPTime/data/processed/FRED_small
      #M4: GPTime/data/processed/M4
      M4: /work/erikde/data/processed/M4/
    frequencies:  
      Y: False
      Q: False
      M: True
      W: False
      D: False
      H: False
      O: False
    min_lengths:
      #Y: 11
      #Q: 11
      #M: 11
      #W: 11
      #D: 11
      #H: 11
      #O: 11
      Y: 9
      Q: 12
      M: 27
      W: 13
      D: 14
      H: 48
      O: 20 
    cutoff_date:
  scaling:
    periods:
      Y: 1
      Q: 4
      M: 12
      W: 1
      D: 1
      H: 24
      O: 1

train:
  #scaler_module: GPTime.utils.scaling
  #scaler_name: MASEScaler
  #scaler_module: GPTime.utils.scaling
  #scaler_name: NoScaler
  scaler_module: sklearn.preprocessing
  scaler_name: MaxAbsScaler
  train_set_size: 0.95
  val_set_size: 0.05
  test_set_size: 0
  num_tests_per_ts: 1
  max_epochs: 15
  early_stop_tenacity: 1000
  log_freq: 5
  clip_gradients: True
  tensorboard_log_dir: GPTime/models/runs/
  model_save_path: GPTime/models/
  # Change model here
  model_module: "GPTime.networks.mlp"
  model_name: "MLP"
  #model_module: "GPTime.networks.ar"
  #model_name: "AR"
  model_params_ar:
    in_features: 100
    out_features: 1
    bias: True
  model_params_mlp:
    in_features: 108
    out_features: 1
    num_layers: 10
    n_hidden: 512
    bias: True
    residual: None
    res_block_size: 3
    skip_connections: False
  model_params_tcn:
    in_channels: 1,
    channels: [32,32,32]
    kernel_size: 4,
    dropout: 0.2
  optimizer_module: "torch.optim"
  optimizer_name: "Adam"
  optimizer_params:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 0.00000001
    weight_decay: 0
    amsgrad: False
  criterion_module: GPTime.utils.loss
  criterion_name: mase_loss
  criterion_params:
    test: None
  #criterion_module: "torch.nn"
  #criterion_name: "L1Loss"
  #criterion_params:
    #size_average: True
    #reduce: True
    #reduction: "mean"
  #criterion_name: "MSELoss"
  #criterion_params:
    #size_average: True
    #reduce: True
    #reduction: "mean"
  dataloader_module: "torch.utils.data"
  dataloader_name: "DataLoader"
  dataloader_params:
    batch_size: 1024
    shuffle: True
    num_workers: 1

evaluate:
  results_path: GPTime/models/

predict:

networks:
  tcn:
    weight_norm: True
  mlp:
  ar:

scoring:
  owa:
    naive2:
      smape:
        yearly: 16.342
        quarterly: 11.012
        monthly: 14.427
        weekly: 9.161
        daily: 3.045
        hourly: 18.383
        global: 13.564
      mase:
        yearly: 3.974
        quarterly: 1.371
        monthly: 1.063
        weekly: 2.777
        daily: 3.278
        hourly: 2.396
        global: 1.912
  metrics:
    mase: True
    smape: True
    owa: True
    mae: False
    rmse: False
    wape: False
    mape: False
  m4:

    #scale_mase: True
    horizons:
      yearly: 6
      quarterly: 8
      monthly: 18
      weekly: 13
      daily: 14
      hourly: 48
    periods:
      yearly: 1
      quarterly: 4
      monthly: 12
      weekly: 1
      daily: 1
      hourly: 24
      other: 1

tests:
  data:
    M4:
      Dtest: "GPTime/tests/data/M4test/Daily-test.csv"
      Htest: "GPTime/tests/data/M4test/Hourly-test.csv"
      Mtest: "GPTime/tests/data/M4test/Monthly-test.csv"
      Qtest: "GPTime/tests/data/M4test/Quarterly-test.csv"
      Wtest: "GPTime/tests/data/M4test/Weekly-test.csv"
      Ytest: "GPTime/tests/data/M4test/Yearly-test.csv"
      Dtrain: "GPTime/tests/data/M4train/Daily-train.csv"
      Htrain: "GPTime/tests/data/M4train/Hourly-train.csv"
      Mtrain: "GPTime/tests/data/M4train/Monthly-train.csv"
      Qtrain: "GPTime/tests/data/M4train/Quarterly-train.csv"
      Wtrain: "GPTime/tests/data/M4train/Weekly-train.csv"
      Ytrain: "GPTime/tests/data/M4train/Yearly-train.csv"
      smyl: "GPTime/tests/data/M4submissions/submission-118.csv"
      montero: "GPTime/tests/data/M4submissions/submission-245.csv"
      naive: "GPTime/tests/data/M4submissions/submission-Naive.csv"
      naive2: "GPTime/tests/data/M4submissions/submission-Naive2.csv"
    
figures:
  path: figures/
