path:
  FRED:
    meta: GPTime/data/meta/FRED/
    #raw: GPTime/data/raw/FRED/
    raw: /work/erikde/data/raw/FRED
  M4:
    raw_train: GPTime/data/raw/M4/M4train/
    raw_test: GPTime/data/raw/M4/M4test/
    meta: GPTime/data/meta/M4/M4-info.csv
api:
  FRED:
    limit: 115
    sleep: 60 
files_per_folder: 100
samples_per_json: 2000